version: '3.8'

services:
  file-monitor:
    build:
      context: .
      dockerfile: Dockerfile-r6-dissect-runner  # Ensure the Dockerfile name matches
    ports:
      - "5000:5000"
    user: root
    environment:
      - FLASK_ENV=development  # Optionally set Flask environment variables
    
  file-upload:
    build:
      context: .
      dockerfile: file-upload-app\Dockerfile-file-upload
    ports:
      - "5001:5001"
    user: root
    environment:
      - NODE_ENV=development
