version: '3.8'

services:
  file-monitor:
    build:
      context: .
      dockerfile: dissect-runner/Dockerfile-r6-dissect-runner
    ports:
      - "5000:5000"
    user: root
    environment:
      - FLASK_ENV=development

  file-upload:
    build:
      context: .
      dockerfile: file-upload-app/Dockerfile-file-upload
    ports:
      - "5001:5001"
    user: root
    environment:
      - NODE_ENV=development

  file-export:
    build:
      context: .
      dockerfile: export-runner/Dockerfile-r6-dissect-export-runner
    ports:
      - "5002:5002"
    user: root
    environment:
      - FLASK_ENV=development

  sheets-export:
    build:
      context: .
      dockerfile: sheets-export-runner/Dockerfile-sheets-exporter
    ports:
      - "5003:5003"
    user: root
    environment:
      - FLASK_ENV=development
      - GOOGLE_SERVICE_ACCOUNT_JSON=${GOOGLE_SERVICE_ACCOUNT_JSON}
