name: Deploy to AWS EC2

on:
  push:
    branches:
      - main  # Set this to the branch you want to deploy from

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ec2-35-177-150-58.eu-west-2.compute.amazonaws.com >> ~/.ssh/known_hosts

    - name: Create .env file on EC2
      run: |
        echo "GOOGLE_SERVICE_ACCOUNT_JSON='${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}'" | ssh ec2-user@ec2-35-177-150-58.eu-west-2.compute.amazonaws.com 'cat > /home/ec2-user/r6-dissect-TL-Fork/.env'

    - name: Deploy to EC2
      run: |
        ssh ec2-user@ec2-35-177-150-58.eu-west-2.compute.amazonaws.com "mkdir -p /home/ec2-user/r6-dissect-TL-Fork"
        rsync -avz --exclude '.git' --exclude 'node_modules' ./ ec2-user@ec2-35-177-150-58.eu-west-2.compute.amazonaws.com:/home/ec2-user/r6-dissect-TL-Fork
        ssh ec2-user@ec2-35-177-150-58.eu-west-2.compute.amazonaws.com "sudo mkdir -p /etc/TLMRIS && cd /etc/TLMRIS && sudo find . -maxdepth 1 ! -name 'data' ! -name '.' -exec rm -rf {} +"
        ssh ec2-user@ec2-35-177-150-58.eu-west-2.compute.amazonaws.com "sudo mv /home/ec2-user/r6-dissect-TL-Fork/* /etc/TLMRIS"
        ssh ec2-user@ec2-35-177-150-58.eu-west-2.compute.amazonaws.com "cd /etc/TLMRIS/scripts && pwd && sudo bash build.sh"
        
